### ISSUE TITLE
Various Syntax highlighting

### ISSUE THREAD

**Issue by Hovestar** [APerricone/harbourCodeExtension#54]
![image](https://user-images.githubusercontent.com/3644064/75802925-90b60600-5d4b-11ea-80ce-749e131072a6.png)

The each in for each is not highlighted. 

![image](https://user-images.githubusercontent.com/3644064/75803018-b80cd300-5d4b-11ea-9d0a-36f2503ea71c.png)

The #elif and #endif directives don't highlight (xHarbour). May be caused by the defined() in the condition

I'd be happy to help if you point me in the right direction.

**Comment by APerricone** [comment]
Many thanks for the report.
the **#elif** **#else** are not highlighted because are inside a *class* definition.  outside they are.

If you are curious the language definition is in file [harbour.tmLanguage.json](https://github.com/APerricone/harbourCodeExtension/blob/master/client/syntaxes/harbour.tmLanguage.json) created by @edgardmessias 

Anyway I will fix it soon, but I don't know when I will release a new version. 
If you see anything else feel free to report them.

**Comment by edgardmessias** [comment]
Hello
Please attach the source with problem and I can try find the problem.

**Comment by edgardmessias** [comment]
The problem occurs when the syntax try start a directive and class at same time.
`if -> endif` and `create class -> endclass`
