### ISSUE TITLE
memvar aliasing syntax highlighting

### ISSUE THREAD

**Issue by Hovestar** [APerricone/harbourCodeExtension#58]
Syntax highlighting is broken after aliasing into memvar:
![image](https://user-images.githubusercontent.com/3644064/77681268-772f6500-6f6b-11ea-837d-f72844d0daa1.png)

**Comment by APerricone** [comment]
it is valid code? memvar is a keyword, like local, public etc etc

**Comment by mlacecilia** [comment]
Hi Seth,
field-> and memvar-> (and its abbreviation m->) are special aliases to
specify the type or the scope of the referenced symbol name.
field-> assures that the symbol is linked to the corresponding fieldname in
the current work area.
memvar-> or m-> assures that the symbol is linked to the corresponding
private memory variable instead of a same named local, static or field item.


Il ven 27 mar 2020, 06:40 Antonino Perricone <notifications@github.com> ha
scritto:

**Comment by mlacecilia** [comment]
Sorry,
I was replying to Antonino, not to Seth...

Il ven 27 mar 2020, 10:20 Maurizio la Cecilia <m.lacecilia@gmail.com> ha
scritto:

**Comment by edgardmessias** [comment]
I am working on it
